#!/bin/bash

# export SSL_CERT_FILE="/Users/justin/.pyenv/versions/3.11.3/lib/python3.11/site-packages/certifi/cacert.pem"
# export REQUESTS_CA_BUNDLE="/Users/justin/.pyenv/versions/3.11.3/lib/python3.11/site-packages/certifi/cacert.pem"
# export REQUESTS_CA_BUNDLE=/opt/homebrew/etc/openssl@3/cert.pem
# export SSL_CERT_FILE=/opt/homebrew/etc/openssl@3/cert.pem
# env

# CERT_PATH=$(python -m certifi)
# export SSL_CERT_FILE=${CERT_PATH}
# export REQUESTS_CA_BUNDLE=${CERT_PATH}

./script/fetch -z 19 \
  -x0 83513 \
  -y0 187554 \
  -x1 83566 \
  -y1 187555 \
  --layer="Tippah_6n12_2015.sid" \
  --url="http://gis.mississippi.edu/server/rest/services/Raster/LocalHighRes_Feb_2023/MapServer" \
  --route="Tippah_6n12_2015" 